### DISCUSSION TITLE
Add support for named enums

### DISCUSSION THREAD

**Discussion by Colmea** [astahmer/typed-openapi#30] [Ideas]
Hi all,

I don't want to create an issue since this feature is not officially supported in the OpenAPI spec, but I think we can trigger a discussion on this topic:
**How to support named enums ?**

Currently, none of the 2 solutions proposed below generate a proper typescript enum.

Few solutions has been proposed:

## Support custom x- property
Adding a custom "x-..."property in the OpenAPI schema. 
- **NSwag** support "x-enumNames"
- **AutoRest** support "x-ms-enum"

Example:
```
"SortDirection": {
  "type": "integer",
  "x-enumNames": ["Asc", "Desc"],
  "enum": [0, 1]
},
```

Few typescript codegen tool support this:
- [openapi-typescript-codegen](https://github.com/ferdikoomen/openapi-typescript-codegen) support the "x-enum-varnames" property
- [openapi-typescript](https://github.com/drwpow/openapi-typescript) support the "x-enumNames" from NSwag

## Use "oneOf" from OpenAPI 3.1

This is the official OpenAPI response on this.
use oneOf combined with "title" and "const":
```
Severity:
  type: integer
  oneOf:
  - title: HIGH
    const: 2
    description: An urgent problem
  - title: MEDIUM
    const: 1
  - title: LOW
    const: 0
    description: Can wait forever
```

I'm not a big fan on this because it's not supported by OpenAPI codegen tools.

===

Do you have any input on this @astahmer ?

Btw, I would be happy to propose a PR to support the first solution
