### ISSUE TITLE
io-ts: optional query parameters are not really optionals

### ISSUE THREAD

**Issue by Colmea** [astahmer/typed-openapi#28]
Hi @astahmer,

First thanks for the lib!

I'm not sure if it's a `typed-openapi` or `typebox-codegen`related bug, but optional query parameters are not properly managed for the io-ts runtime. 

Take this endpoint from the PetStore schema, where the `tags` query param is not required:
```
  /pet/findByTags:
    get:
      parameters:
        - name: tags
          in: query
          description: Tags to filter by
          required: false
          explode: true
          schema:
            type: array
            items:
              type: string
```

Generate this io-ts codec and type:
```
export type get_FindPetsByTags = t.TypeOf<typeof get_FindPetsByTags>;
export const get_FindPetsByTags = t.type({
  method: t.literal("GET"),
  path: t.literal("/pet/findByTags"),
  parameters: t.type({
    query: t.type({
      tags: t.union([t.undefined, t.array(t.string)]),
    }),
  }),
  response: t.array(t.number),
});

// Generated type from codec looks like this
type get_FindPetsByTags = {
    method: "GET";
    path: "/pet/findByTags";
    parameters: {
        query: {
            tags: string[] | undefined;
        };
    };
    response: number[];
}
```

This type is not correct, `tags` should be optional.

A more correct approach imho would be to move all optional params inside a `t.partial` (see doc https://github.com/gcanti/io-ts/blob/master/index.md#mixing-required-and-optional-props):

```
export const get_FindPetsByTags = t.type({
  method: t.literal("GET"),
  path: t.literal("/pet/findByTags"),
  parameters: t.type({
    query: t.intersection([
      // required params
      t.type({
        requiredParam: t.array(t.string),
      }),
      // optional params
      t.partial({
        tags: t.array(t.string),
      }),
    ]),
  }),
  response: t.array(t.number),
});
```

Is there a bug or maybe I'm missing something ?

Thank you for your help!
