### ISSUE TITLE
Allow for mixing optional and required parameters in query parameters

### ISSUE THREAD

**Issue by 0237h** [astahmer/typed-openapi#33]
Hello,

I've noticed that the code generation doesn't allow for having both required **and** optional parameters for an endpoint.

[Example](https://typed-openapi-web.vercel.app/?input=N4KABGBED2AOCmA7AhrAlpAXFAzAOgAZDIAacKNRAM2izFAgkgBc1mAbeOyAFXgGdmYAIIAFAJKlyTAG7wATvzTRE3IusjkAvmSaxkzABb86DRpAD0zAc1PTzAc3i3sZxubgKDyxOIAm3NaCUu7ukPryyAC2zgom2ADa9qH0ySlQKDGBNgD68vAAjgCuaPkBuulhlNzFCgCeIZXm%2BcWl8AHYzPJF8BVNUPwAxobwUch2-WHMdQjcgvKUDpqTYFpp7jrrjG5NkJlc2Cy5cKwqyOw5AIyN-ZDVh7XyDX27LSVldFTn-L1bYUMjMYTFZQaazQ7zRbLSZrfqbfo7Sp7aIHUHHWCnFAXABMN129ygj2ef2ahXe7U%2B31%2BK0gANG41cJKmM1RtK6UKZqxJsPSAF0XmF8vxYCofvFUrc-PAvkV2C4JZNIFKhgsMT5uMJEGAioh4AAPBCDax%2BMAKeTQeRgIUixA-PB4pGDFTWRDyxG7VCwdhoQbeFQWABW-BUph5cO5WzDjCjPPhUCdURtSGY4rMazWQA)
```yaml
"parameters": [
  {
    "name": "test_required",
    "in": "query",
    "required": true,
    "schema": {
      "type": "string"
    }
  },
  {
    "name": "test_optional_1",
    "in": "query",
    "required": false,
    "schema": {
      "type": "string"
    }
  },
  {
    "name": "test_optional_2",
    "in": "query",
    "required": false,
    "schema": {
      "type": "string"
    }
  }
]
```
will generate
```ts
parameters: {
  query: { test_required: string; test_optional_1: string; test_optional_2: string };
};
```
If all parameters are set with `required: false`, the [codegen](https://typed-openapi-web.vercel.app/?input=N4KABGBED2AOCmA7AhrAlpAXFAzAOgAZDIAacKNRAM2izFAgkgBc1mAbeOyAFXgGdmYAIIAFAJKlyTAG7wATvzTRE3IusjkAvmSaxkzABb86DRpAD0zAc1PTzAc3i3sZxubgKDyxOIAm3NaCUu7ukPryyAC2zgom2ADa9qH0ySlQKDGBNgD68vAAjgCuaPkBuulhlNzFCgCeIZXm%2BcWl8AHYVMjs-PAVTVD8AMaG8FHIdgNhzHUI3ILylA6aU2Baae46G4xuTZCZXNgsuXCsKt05AIyNA5DVR7XyDf17LSVldF09fdthw6PjSarKAzOZHBZLFZTdYDLYDXaVfbRQ4gk6wM4odg5ABMNz29ygj2ev2ahXe7U%2B3V6L0R-zGE1cJOmsxRkAhiGWTLWJJh6QAujTSfxYCpevFUrc-PAukV2C4JVNIFLhot0T5uMJEGAioh4AAPBBDax%2BMAKeTQeRgfLC0XwPB4xFDFTWRDyhF7VCwdhoIbeFQWABW-BUpl5sJ52zDjCjvLhUCdURFutd4rM63WQA) works as expected:
```ts
parameters: {
  query: Partial<{ test_required: string; test_optional_1: string; test_optional_2: string }>;
};
```
I believe that the issue comes from this code that checks for `lists.query.every`, is there a way to fix this behavior perhaps ?
https://github.com/astahmer/typed-openapi/blob/main/packages/typed-openapi/src/map-openapi-endpoints.ts#L88
```ts
// Make parameters optional if none of them are required
if (params) {
  const t = createBoxFactory({}, ctx);
  if (params.query && lists.query.length && lists.query.every((param) => !param.required)) {
    if (!params.query) params.query = {};
    params.query = t.reference("Partial", [t.object(params.query)]) as any;
  }
[...]
```
