### ISSUE TITLE
Default values from schema not passed through codegen

### ISSUE THREAD

**Issue by 0237h** [astahmer/typed-openapi#34]
Hi,

Seems like when applying default values to some parameters in the OpenAPI spec, those defaults are not carried over in the codegen. This could be useful especially for Zod, etc. when parsing the resulting objects to provide the default value.

[Example](https://typed-openapi-web.vercel.app/?input=N4KABGBED2AOCmA7AhrAlpAXFAzAOgAZDIAacKNRAM2izFAgkgBc1mAbeOyAFXgGdmYAIIAFAJKlyTAG7wATvzTRE3IusjkAvmSaxkzABb86DRpAD0zAc1PTzAc3i3sZxubgKDyxOIAm3NaCUu7ukPryyAC2zgom2ADa9qH0ySlQKDGBNgD6iNA5fvBUyACu7La66WGU3ACOpQoAniHV5vwAxobwUch2baEsTQjcgvKUDpoDEFpp7jpzjG5tkJlc2Cy5AO5shoXFZRWtA5C1Gw3Nxyud3b3900zMw%2BtQYxNXJ0Ul5S5Q3ezsaBgLbQeTsAKLeaQsCzaoAXSqKUg8gEsBU-AE92qkC%2Bh1%2By2xRU641grBU3GEiDApUQ8AAHggOtY-GAFPJQWAUfw0YgMXgPulIB0VNZEPjoWFULB2GgOt4VBYAFb8cmuWHTdXVTWhbUzezqhZMYVRHlIZjxVJ62ZAA)
```yaml
"parameters": [
  {
    "name": "test_no_default",
    "in": "query",
    "schema": {
      "type": "string"
    }
  },
  {
    "name": "test_with_default",
    "in": "query",
    "schema": {
      "type": "string",
      "default": "hello world"
    }
  }
]
```
will generate
```ts
parameters: z.object({
  query: z.object({
    test_no_default: z.string().optional(),
    test_with_default: z.string().optional(),
  }),
})
  ```
instead of
```ts
parameters: z.object({
  query: z.object({
    test_no_default: z.string().optional(),
    test_with_default: z.string().optional().default("hello world"),
  }),
})
```
